build: image_processing                                                         
image_processing: main.c bmp_header.h                                           
        gcc -Wall main.c -o image_processing                                    
                                                                                
run: image_processing                                                           
        ./image_processing                                                      
                                                                                
clean:                                                                          
        rm image_processing                                                     
~                               
